### ISSUE TITLE
Avoid shell scripts

### ISSUE THREAD

**Issue by chrisparnin** [alt-code/AutoSpark#19]
As much as possible, avoid use of shell scripts in building this tool. Either use node.js or python as the engine driving the program.

Use package managers to specify dependencies, not shell scripts.

**Comment by sjoshi6** [comment]
Got it. I will re write parts of code used to launch the cluster using node.js

**Comment by sjoshi6** [comment]
Converting shell scripts to python / js scripts
- [x] AWS Launcher shell script to python launcher
- [x] Digital Ocean shell script to python launcher
