### ISSUE TITLE
Identify the best method to authorize SSH public keys to cluster instances

### ISSUE THREAD

**Issue by sjoshi6** [alt-code/AutoSpark#3]
- [x] Read documentation of how SSH authorization works
- [x] Start using Ansible playbooks by manually configuring SSH Public keys in cloud instances
- [x] Determine API calls for AWS and Digitial Ocean to insert additional SSH authorized public keys.

**Comment by chrisparnin** [comment]
I recently had to do this for setting up things when playing with vagrant for one of the workshops.

This is how I did things manually, so you can think about automating it:

```
$ ssh-keygen -t rsa -f spark -C sparkUser
# Get things into clipboard
$ pbcopy < spark.pub
# Inside machine you want to ssh into:
$ vim ~/.ssh/authorizedkeys
# paste key into, save
```

Now you can ssh into your spark machine:
```
ssh -i spark sparkUser@machine
```

With ansible, you just set your inventory to have `ansible_ssh_private_key_file=./spark`

https://github.com/CSC-DevOps/Course/blob/master/Workshops/CM.md

For digitalocean, you can do this one time manually, then inside your request to make a new machine, give it sshkey=[323232], which is id of your key stored with digitalocean.
