### ISSUE TITLE
autospark on HPC?

### ISSUE THREAD

**Issue by timm** [alt-code/AutoSpark#39]
would autospark simplify/ complicate the task of booting spark on NC state's HPC?

**Comment by sjoshi6** [comment]
Dear Dr. Tim,

Currently autospark does not support a cluster launch on VCL. 

However the only missing part is to start a group of instances on VCL.
 rest all steps could be reused as they are primarily based on Ansible / Python.

Dr. Parnin has created a new git issue to onboard VCl as a driver.

**Comment by chrisparnin** [comment]
The main issue I think with HPC is that you don't get to control to software/images. You have to do everything in userspace.
https://www.ncsu.edu/hpc/About/Services.php

@sjoshi6 How much would ansible still be able to work without root access?

Otherwise, #40 might be a good alternative, and it follows the google way. Many cheap nodes do the job well.

**Comment by sjoshi6** [comment]
I have not experimented with VCL HPC. I would have to give it a run and then confirm how much of it works without root access

**Comment by chrisparnin** [comment]
@sjoshi6 Tim will probably have a student investigate over the break. Thanks!

**Comment by chrisparnin** [comment]
@dichen001 Can you write your notes about getting spark on HPC here when you're done playing with it? That will be useful for setting up autospark to work with HPC.

**Comment by dichen001** [comment]
Sure. Should I write directly following this issues?

**Comment by chrisparnin** [comment]
Can create a markdown file in this repo and link to it.

**Comment by dichen001** [comment]
OK. I will do it soon.

**Comment by dichen001** [comment]
@chrisparnin just finished 1st version. 

Hi, @imaginationsuper  @amritbhanu could you help test if you can install Spark on HPC follow my notes [here](https://github.com/alt-code/AutoSpark/blob/4b1940c27342181c2a9dbc1506535126375d14fa/Note%20for%20Spark%20installation%20on%20HPC.md).  If there is any problem with it, please let me know. 
Thanks.

**Comment by amritbhanu** [comment]
Thanks to you. I am able to successfully install spark on HPC.

**Comment by chrisparnin** [comment]
Closing for now.
