### ISSUE TITLE
Integrate VLC driver as provider option

### ISSUE THREAD

**Issue by chrisparnin** [alt-code/AutoSpark#40]
You can connect to VCL over XML-RPC: https://arjie.com/2014/04/10/using-the-vcl-xml-rpc-interface-with-python/

* [ ] Can use this example as [a starting place](https://github.ncsu.edu/cjparnin/vcl-opsworks).

**Comment by amritbhanu** [comment]
@chrisparnin 
Prof., while connecting to VCL over XML-RPC, I am getting an error. Can you help me on this?

```
hosts {'152.46.17.86': {'ansible_ssh_host': '152.46.17.86', 'ansible_ssh_port': 22, 'ansible_ssh_user': 'aagrawa8'}}

PLAY [all] ******************************************************************** 

GATHERING FACTS ***************************************************************
fatal: [152.46.17.86] => SSH Error: Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).
    while connecting to 152.46.17.86:22

```

**Comment by chrisparnin** [comment]
Will want to try `ssh aagrawa8@152.46.17.86` to see if you can login manually.

**Comment by amritbhanu** [comment]
No, I can't. I am assigned this IP address (152.7.98.223) to log onto VCL.
I am wondering where can I manually change the IP while using the commands?

**Comment by sjoshi6** [comment]
Maybe this would help.

There is a hosts file called inventory typically found along with anisble
playbook which has the list of IPs. you could use that to specify your IP
Address manually.

**Comment by chrisparnin** [comment]
In this case, I think the inventory is supposed to be built dynamically by the python code. Would have to see why its using a hardcoded or wrong ip.

**Comment by sjoshi6** [comment]
Yes , The inventory file is created by python dynamically. And it should write out the IP addresses of the instances that it launched .
An incorrect IP address in inventory could be added due to a failed previous run. Re running the cluster launch on a cloud vendor could resolve this. However the system only supports aws and digital ocean. Therefore an instance launched on VCL would need to be added manually in the inventory file.
Sent from Outlook Mobile




On Mon, Jan 11, 2016 at 10:39 AM -0800, "Chris Parnin" <notifications@github.com> wrote:












In this case, I think the inventory is supposed to be built dynamically by the python code. Would have to see why its using a hardcoded or wrong ip.

**Comment by amritbhanu** [comment]
@chrisparnin Professor, for connecting to VCL, it always prompt for user and pass. For launching multiple instances it will ask again and again.

I don't see any ssh lib support in xmlrcplib package. I want to uniquely identify the instances with the ssh private and public keys.

**Comment by chrisparnin** [comment]
The way to solve this "manually" is to copy the ssh_key into VCL first (or
see if there is a way to do this automatically when reserving).

**Comment by amritbhanu** [comment]
I will look into the above soon.

In the meantime, I am having another issue of running any tasks using ansible playbook to run on the vcl hosts. This is what was happening at the original run [a starting place]  (https://github.ncsu.edu/cjparnin/vcl-opsworks) as well.
And Its throwing the same error again.
```
PLAY [all] ******************************************************************** 

GATHERING FACTS ***************************************************************
fatal: [152.46.17.86] => SSH Error: Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).
    while connecting to 152.46.17.86:22

```

I am seeing some permission issues.
Any help in this regard would be great
