### ISSUE TITLE
please add to alt-code

### ISSUE THREAD

**Issue by timm** [alt-code/AutoSpark#41]
@imaginationsuper 

@dichen001

@amritbhanu

**Comment by chrisparnin** [comment]
Added.

**Comment by timm** [comment]
@imaginationsuper
@dichen001 
@amritbhanu

please review the issue track https://github.com/alt-code/AutoSpark/issues/39

**Comment by amritbhanu** [comment]
yes dr menzies, I am on it.

**Comment by dichen001** [comment]
Hi Dr. @timm ,
I have looked through this project and figure out how it works. You want us to focus on booting up spark on HPC and leave VCL alone, right?  Still need some time to find out how many existing code we can use on HPC.  

Hi @amritbhanu @samrudhisharma ,
I am in our lab most of the time.  Welcome for you guys to join me here if you want to discuss in person. 

-Jack

**Comment by dichen001** [comment]
Anyone succeed in installing Spark on HPC?   I have tried to fix the error below during installment, but making no progress.  Any advice will be appreciated.
```
[error] Required file not found: sbt-interface.jar
[error] See zinc -help for information about locating necessary files
```

**Comment by chrisparnin** [comment]
Are you using `build/mvn` to install?

**Comment by chrisparnin** [comment]
Have you considered a pre-built package instead of from source?

**Comment by dichen001** [comment]
I remember I tried.  But it has been for a while. Not so sure about that. I will start over again, and see how it goes.
