### ISSUE TITLE
Project Proposal

### ISSUE THREAD

**Issue by chrisparnin** [alt-code/AutoSpark#42]
Please draft project proposal in comments here.

**Comment by gohilankit** [comment]
Title : Auto configuration of Apache Spark Cluster and HDFS on NCSU VCL and HPC nodes

Summary :
Apache Spark is an open source cluster computing framework and one of the top Apache projects.It can be used for batch processing, running iterative algorithms as well as stream processing and has proven to offer a better performance than the traditional Hadoop Map Reduce tasks. Spark is designed to operate in a distributed setup, thus allowing the researchers / users to reduce the time it takes to produce valuable results from massive data sets. Spark can read and write data from a local filesystem as well as any distributed filesystem like Amazon S3 and HDFS. Using Spark and HDFS together can offer powerful capabilites which can be leveraged by writing minimal code to compute in parallel over large data sets.

One typical challenge in using Spark for processing large datasets is to setup a elastic cluster on demand. Spark setup requires a significant number of configuration steps. Repeating the same set of configurations time and again is inefficient. As a part of the independent study under Dr. Parnin, I wish to extend the project for auto configuring Spark cluster on AWS to NCSU VCL and HPC nodes. I intend to automate the process of launching and using an on demand Spark cluster. This project would enable a users/researchers at NC State to quickly setup a Spark cluster on VCL nodes, avoiding the need to resort to commercial cloud providers, and leverage the power of Spark processing for large-scale data processing.

Project Goals and Tasks 
- Identifying and enumerating the best approaches of setting up a Spark cluster.
- Prototyping the approach of cluster setup on NCSU VCL nodes.
- Running a text analysis job on a single machine vs a spark cluster and collecting performance results.
- Building a usable Python / Javascript project to perform auto configuration of Apache Spark cluster.
- Determine the possibility of deploying Spark as Docker container images.
- Running test jobs on the auto configured Spark clusters to collect results on the datasets provided by Dr. Parnin.
- Experimenting with other commonly used Spark jobs and open source data sets. 
- Identifying whether the project can be leveraged for other distributed systems like Apache Kafka, Apache Storm or Hadoop.

**Comment by chrisparnin** [comment]
Looks good. 
Please save as a pdf and follow instructions here for registering for research credits:
https://www.csc.ncsu.edu/dgp/researchcredits.html

**Comment by gohilankit** [comment]
Registration complete. Closing the issue.
