### ISSUE TITLE
Some extra permissions may be needed from HPC

### ISSUE THREAD

**Issue by dichen001** [alt-code/AutoSpark#44]
Still stuck by the permission issues on HPC.  Without 'sudo', we could not install Spark on HPC. Tried Docker too, but Docker has to deal with the OS. So it also need root permission. 

I am just wondering if we could get some extra permissions from HPC.  If anyone has any idea for installing Spark without using the root permission, please share here.

Also, I wrote a email to the help-desk, asking for some help for installing Spark. Let's see how they will reply.

**Comment by chrisparnin** [comment]
You'd have to install the dependencies locally. Docker would most likely be a no go, as HPC cluster is probably so old, it won't have the necessary linux kernel  updates.

Supposedly, this works even on a Raspberry Pi 2: https://darrenjw2.wordpress.com/2015/04/17/installing-apache-spark-on-a-raspberry-pi-2/

**Comment by dichen001** [comment]
Hi @chrisparnin , thanks for your reply.

I do have tried to install all the Spark dependencies locally, but the problem stops me is in the end of #41.  Any idea for those errors?

**Comment by chrisparnin** [comment]
Instructions used for setting up spark on AWS might be helpful, but would have to substitute how to deal with things questions like, is there java 7 available, etc?

https://github.com/alt-code/AutoSpark/blob/master/Notes/spark_setup.md

**Comment by dichen001** [comment]
As you can see for the installment on AWS, almost every step uses 'sudo'.  I believe all the dependencies for installing Spark locally, like Java, sbt, Maven etc, should have been installed on my HPC account.  Maybe I should start over again and see if I can find any problem.

Thanks again.

**Comment by chrisparnin** [comment]
Except for apt-get to install java, none of the commands should need `sudo`.

Have you tried one of the pre-built binaries, such as:
http://apache.mirrors.hoobly.com/spark/spark-1.4.1/spark-1.4.1-bin-hadoop2.6.tgz

**Comment by dichen001** [comment]
Hi @chrisparnin , Problem solved.  Pre-built binaries works.  Thanks a lot.

**Comment by chrisparnin** [comment]
:+1:
