### ISSUE TITLE
Wikipedia experiment replication...

### ISSUE THREAD

**Issue by chrisparnin** [alt-code/AutoSpark#51]
http://www.dmtk.io/lightlda.html

> We report the performance of LightLDA on two public available datasets, Wiki2014 and ClueWeb09(English version), for your reference. The statistics* of these datasets and the performance of LightLDA are given as follows. Both experiments ran on a cluster consisting of 256GB-RAM 20-core machines.

**Comment by gohilankit** [comment]
Not moving forward with Microsoft's DMTK.
