### ISSUE TITLE
SSH Key Setup for VLC

### ISSUE THREAD

**Issue by chrisparnin** [alt-code/AutoSpark#52]
Try to setup the system by just getting a keypair generated.

Test with ssh -i private_key

http://askubuntu.com/a/4833

> ssh-copy-id user@hostname.example.com

**Comment by amritbhanu** [comment]
first success,

able to copy the ssh-key and able to load the packages. 

![file](https://github.com/alt-code/AutoSpark/raw/master/Amrit/01-27/Screenshot%20from%202016-01-27%2016:43:20.png)

Next steps are communicating with the slave nodes.
