### ISSUE TITLE
A failure while submitting the job

### ISSUE THREAD

**Issue by amritbhanu** [alt-code/AutoSpark#55]
I was able to successfully submit a job on master node which is being distributed to its 2 worker nodes.
But it failed to process it because of some extra thresholds set on the hardware of system which VCL instances aren't providing. I used the default config for setting the spark which needs to be changed. I am working on it.

In the meantime, figure shows the worker nodes and the following error.

![file] (https://github.com/alt-code/AutoSpark/raw/master/Amrit/02-15/Screenshot%20from%202016-02-15%2017:57:36.png)

**Comment by amritbhanu** [comment]
## Experiment on CS.txt (7 MB) file
### Results are successful.
 - The total time taken by each node and the tast distributed across slave nodes can be seen.
![file] (https://github.com/alt-code/AutoSpark/raw/master/Amrit/02-15/cs_lda.png) 

## Experiment on jones.txt (84 MB) file
 - It didnt succeed by ending abruptly throwing Out of memory error. It happened initially with our experiments before we switched to AWS.
 - I am not able to reserve more than 4 nodes so I haven't tested with better config for such a large file.

**Comment by amritbhanu** [comment]
## Experiment on CS.txt (7 MB) file
### Results are successful.
 - The total time taken by each node and the tast distributed across slave nodes can be seen.

![file] (https://github.com/alt-code/AutoSpark/raw/master/Amrit/02-15/cs_lda_4.png) 

## Experiment on jones.txt (84 MB) file

 - It didnt succeed by ending abruptly throwing Out of memory error. It happened initially with our experiments before we switched to AWS.
 - I am not able to reserve more than 4 nodes so I haven't tested with better config for such a large file.

**Comment by gohilankit** [comment]
Try changing the driver memory and executor memory parameters while submitting the job.

**Comment by amritbhanu** [comment]
## Tasks @gohilankit 

- Can you try running your experiment again if you haven't got the config file? The parameter which you specified isn't working. It is still giving an error of Out of Memory.

- Your results showed that you have run it with 2g memory but right now I am looking at logs of spark and it took a maximum of 1247mb even when specified large memory of 2g and 3g. And thats the limit of VCL VMs which I was talking about.

**Comment by gohilankit** [comment]
I did the below steps to manually set up a cluster:
1. Copy Spark and hadoop on each node.
2. Set up HDFS for name & data nodes. Add slave IPs in $HADOOP_CONF_DIR/slaves file on master.
Configure $HADOOP_CONF_DIR/hdfs-site.xml, core-site, mapred-site, yarn-site
(Followed [this](http://arturmkrtchyan.com/how-to-setup-multi-node-hadoop-2-yarn-cluster) tutorial to set up HDFS.
4. Start HDFS using start-dfs & start-yarn scripts on name node.
5. Copy the input file on HDFS and modify Spark job to read from HDFS.
6. Start Spark cluster using start-all.sh on Master node.
7. Submit job using the script
 $SPARK_HOME/bin/spark-shell -i --master spark://<master_ip>:<port> lda.scala --executor-memory 2G --driver-memory 1500M

I don't have a script ready yet to automatically configure HDFS & Spark cluster.
Are you doing something differently?

Attaching the result of Spark UI for various runs of experiment on cluster by modifying the executor memory. Notice the 2.9 GB memory allocated to workers. My premise for maximum slave memory was based on this.

![screenshot from 2016-01-26 04-08-28](https://cloud.githubusercontent.com/assets/12588124/13097298/d6a316fc-d4ed-11e5-8a68-b710441fbdb7.png)

**Comment by chrisparnin** [comment]
Autospark doesn't setup a HDFS system by default, so that might be one
difference.

**Comment by gohilankit** [comment]
In my opinion,in cluster computing framework, it will be better to do I/O operations from a distributed file system so that not only input is read from one place but also the results are outputted to the same space. If not HDFS, it can be Amazon S3 or some other DFS.
So it will be a good idea to incorporate HDFS set up in AutoSpark.

**Comment by chrisparnin** [comment]
Yes. I think we played with getting S3 working too.
